name: Deploy Script

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v4  # Set up Python environment
        with:
          python-version: '3.x'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run deploy script
        run: python deploy_to_github.py  # Adjusted to your script's pathway
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's built-in token for authentication
